### ISSUE TITLE
Mistake in documentation of import_from_iterable

### ISSUE THREAD

**Issue by soridev** [exasol/pyexasol#83]
Hi,

There is an issue in the HTTP_TRANSPORT documentation. For the usage of _"import_from_iterable()"_ it shows the following example:

```
def my_generator():
    for i in range(5):
        yield (i, 'Bob', True, '2017-01-01')

C.import_from_iterable(my_generator, "users")
```

Executing this will throw an exception like: "object is not iterable".
Reason for this is the missing round brackets for the generator.

The example should be:

``` 
def my_generator():
    for i in range(5):
        yield (i, 'Bob', True, '2017-01-01')

C.import_from_iterable(my_generator(), "users")
``` 

Thanks and best regards.

**Comment by littleK0i** [comment]
I'll fix it with the next update, thank you!

**Comment by littleK0i** [comment]
Done in https://github.com/exasol/pyexasol/commit/abae5213915fbd95b0bdf9e4c819d979fa45536a
