### ISSUE TITLE
Add job name to .github/workflows/examples.yml

### ISSUE THREAD

**Issue by kaklakariada** [exasol/pyexasol#85]
github-keeper can only update the branch protection in this repo if a job name is defined in `.github/workflows/examples.yml`:

`Validation Error for .github/workflows/examples.yml: matrix github-action jobs with object parameters and no job name are not supported. Please add a name field to the job that combines the matrix parameters into a more readable name. For example "Build with Go ${{matrix.go}} and Exasol ${{ matrix.db }}"`

**Comment by littleK0i** [comment]
@kaklakariada , do you have an example?

I've checked a few other repos in "exasol" org, but I could not find "name" fields being defined explicitly.

Thank you.

**Comment by kaklakariada** [comment]
Hi @littleK0i,
Correct. This is only necessary for workflows with a matrix definition. In order to configure branch protections, github-keeper needs to determine the job name, which is a bit complicated with matrix builds. That's why it requires a job name.

You can use this PR as an example how to add the name: https://github.com/exasol/r-exasol/pull/116/files

**Comment by littleK0i** [comment]
@kaklakariada , is this change good enough?
https://github.com/exasol/pyexasol/commit/1e1d3527ac905a69de83a948fa460a0c7a5f21be

Thank you.

**Comment by kaklakariada** [comment]
Good morning @littleK0i!
Thank you for your changes, but this was not what I meant.
Sorry I didn't explain it correctly. I created PR #87 with the changes to avoid confusion. Please review and check if it's OK for you.

**Comment by littleK0i** [comment]
@kaklakariada , merged it, thank you.

Please note, something is not right with SSL integration test. I guess, something was changed in test containers.

It is not related to job names, must be something else.
