### ISSUE TITLE
Pyexasol with SaaS Authentication error

### ISSUE THREAD

**Issue by exa-eswar** [exasol/pyexasol#86]
While trying to use the pyexasol with newly launched SaaS offering; I got the following error.

Installed latest pyexasol:  Successfully installed pyexasol-0.24.0

Error after running above code: 
C = pyexasol.connect(dsn='SaaSURL.clusters.exasol.com:8563', user='myusername', password='mypwd', compression=True)
df = C.export_to_pandas("SELECT * FROM EXA_ALL_USERS")
print(df.head())

ExaAuthError: 
(
    message     =>  Connection exception - Authentication using OpenID Connect tokens is not supported (requires driver with version 7.1.0 or greater).
    dsn         =>  SaaSURL.clusters.exasol.com:8563
    user        =>  myusername
    schema      =>  
    session_id  =>  
    code        =>  08004
)

Please comment if you require any additional details to reproduce the issue. 

My system details: MacOS Monterey Intel i9, 8 core
However, when I did the same thing with Notebook from Ec2 instance on Ubuntu 20.04, everything works fine. 
![image](https://user-images.githubusercontent.com/97116849/154668985-633f5af9-0600-4376-ae5c-8143a6af983d.png)

**Comment by littleK0i** [comment]
Could you try to enable `debug=True` connection option and attach logs?

Let's see the specific communication.

Thank you.

**Comment by littleK0i** [comment]
Ok, this is simple.

Your local pyexasol version on MacOS is older.

```
"driverName": "PyEXASOL 0.20.0",
"clientName": "PyEXASOL",
"clientVersion": "0.20.0",
```

Update to the latest version to be able to connect to SAAS.

**Comment by littleK0i** [comment]
It needs to be updated in order to work with Exasol SAAS.

OpenID tokens and protocol version 3 are required for SAAS and were implemented in the most recent versions only.

I'll close the issue for now.
