### ISSUE TITLE
Document that Connection sharing with multiprocessing doesn't work with TLS Encryption

### ISSUE THREAD

**Issue by tkilias** [exasol/pyexasol#89]
- Sharing connection between processes created with python multiprocessing doesn't work with TLS Encryption, because the TLS context is not stateless. You, probably, can use the connection in one of the Parent-Child Processes, but not in multiple. 
- For unencrypted connection, it seemed to work a bit more flexible, but was also dangerous 
- We should generally discourage this pattern and propose alternatives, such as
  - Using IPC for coordination between the processes
    - If you need everything in one session, you can use one process for sending queries and the others do the work 
    - Or, if you coordinate multiple sessions in multiple processes, you can create a session in child processes and coordinate them with barriers 
  - Using threading, if the parallel tasks don't create high load and only sending queries.

**Comment by littleK0i** [comment]
Honestly, I do not understand why people keep trying this when clear instructions for parallelism are provided: https://github.com/exasol/pyexasol/blob/master/docs/HTTP_TRANSPORT_PARALLEL.md

threadsafety level is 1: https://github.com/exasol/pyexasol/blob/master/pyexasol/connection.py#L37-L45

Also, there is an exception for attempt to run second request from another thread: https://github.com/exasol/pyexasol/blob/master/pyexasol/connection.py#L514-L518

Connections should not be shared across multiple processes. Connections can be shared across multiple threads, but only thread can run requests in parallel.

If customer wants to run multiple queries in parallel, one connection per query is required.

If customer wants to read large data set in parallel, HTTP transport is the best bet. It requires 1 process for connection and management and any number of worker processes.

**Comment by littleK0i** [comment]
I'll add a page tomorrow, it's ok.

**Comment by tkilias** [comment]
thx

**Comment by littleK0i** [comment]
@tkilias , please take a look:
https://github.com/exasol/pyexasol/blob/master/docs/PARALLELISM.md

**Comment by tkilias** [comment]
thx, looks good.
