### ISSUE TITLE
respect `no_proxy` environment variable

### ISSUE THREAD

**Issue by MM-Lehmann** [exasol/pyexasol#96]
`pyexasol` does pickup my `http_proxy` environment but not the whitelist in `no_proxy`.
I can't see a way in the `ExaConnection` code to explicitly ignore proxy settings once set in the underlying system. Unfortunately, I need the proxy for other connections with other libraries in my project.
I am using pyexasol `0.24.0` as a library in Apache Airflow 2.2.5

**Comment by littleK0i** [comment]
@MM-Lehmann , it looks like underlying WebSocket client picks up `https_proxy` and `http_proxy` from environment. Pyexasol does not explicitly do so.

However, Websocket client does also pick `no_proxy` from environment, according to this code: https://github.com/websocket-client/websocket-client/blob/a8a409999280e8b90d856113cd109a46b1d465b7/websocket/_url.py#L104-L121

Please double-check version of installed Websocket client. This feature was added about a year ago: https://github.com/websocket-client/websocket-client/issues/700
