### ISSUE TITLE
Pyexasol raises FutureWarning

### ISSUE THREAD

**Issue by rvosshall** [exasol/pyexasol#97]
Each time I use [connection.import_from_pandas](https://github.com/exasol/pyexasol/blob/168db3b6c101417a563ea87f927f3bb61579689f/pyexasol/connection.py#L287) the following FutureWarning is raised: 

`FutureWarning: the 'line_terminator'' keyword is deprecated, use 'lineterminator' instead.
  return src.to_csv(wrapped_pipe, header=False, index=False, line_terminator='\n', quoting=csv.QUOTE_NONNUMERIC, **kwargs)`

May be you could already use `lineterminator`  in [callback.import_from_pandas](https://github.com/exasol/pyexasol/blob/168db3b6c101417a563ea87f927f3bb61579689f/pyexasol/callback.py#L81) to avoid this.

**Comment by littleK0i** [comment]
Fixed in `0.25.1`.

Unfortunately, I had to add `packaging` to list of dependencies to check version of `pandas`. Hopefully, I'll find a better solution in future.

**Comment by tkilias** [comment]
Hi @rvosshall and @littleK0i,

I wanted to ask if this issue is done for the moment, such that we can close it?

**Comment by redcatbear** [comment]
Closed due to missing user response.
